apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: spring-server
          {{ with .Values.springContainer }}
          image: {{ .image }}
          imagePullPolicy: {{ .imagePullPolicy }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .profile }}
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /etc/config
              name: configmap
              readOnly: true
            - mountPath: /etc/secret
              name: secret
              readOnly: true
          {{ end }}
      {{ if or .Values.config.enable .Values.secret.enable }}
      volumes:
        {{ if .Values.config.enable }}
        - name: configmap
          configMap:
            name: {{ .Values.name }}-config
            items:
              - key: application-config.yaml
                path: application-config.yaml
        {{ end }}
        {{ if .Values.secret.enable }}
        - name: secret
          secret:
            secretName: {{ .Values.name }}-secret
            items:
              - key: application-secret.yaml
                path: application-secret.yaml
        {{ end }}
      {{ end }}
