apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: spring-server
          {{ with .Values.springContainer }}
          image: {{ .image }}:{{ .version }}
          imagePullPolicy: {{ .imagePullPolicy }}
          {{ if .resources.enabled }}
          resources:
            requests:
              memory: {{ .resources.requests.memory | default "512Mi" }}
              cpu: {{ .resources.requests.cpu | default "250m" }}
            limits:
              memory: {{ .resources.limits.memory | default "1Gi" }}
              cpu: {{ .resources.limits.cpu | default "500m" }}
          {{ end }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .profile }}
            - name: AWS_ACCESS_KEY_ID
              value: {{ .aws.bedrock_access_key_id }}
            - name: AWS_BEARER_TOKEN_BEDROCK
              value: {{ .aws.bearer_token_bedrock }}
            - name: AWS_REGION
              value: {{ .aws.region }}
          ports:
            - containerPort: 8080
              protocol: TCP
              name: http
          {{ end }}
          {{ if or .Values.config.enable .Values.secret.enable }}
          volumeMounts:
            {{ if .Values.config.enable }}
            - mountPath: /etc/config
              name: configmap
              readOnly: true
            {{ end }}
            {{ if .Values.secret.enable }}
            - mountPath: /etc/secret
              name: secret
              readOnly: true
            {{ end }}
          {{ end }}
      {{ if or .Values.config.enable .Values.secret.enable }}
      volumes:
        {{ if .Values.config.enable }}
        - name: configmap
          configMap:
            name: {{ .Values.name }}-config
            items:
              - key: application-config.yaml
                path: application-config.yaml
        {{ end }}
        {{ if .Values.secret.enable }}
        - name: secret
          secret:
            secretName: {{ .Values.name }}-secret
            items:
              - key: application-secret.yaml
                path: application-secret.yaml
        {{ end }}
      {{ end }}
