{{- $root := . }}
{{ range .Values.externalService }}
{{- if .externalName }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $root.Values.namespace }}
spec:
  type: ExternalName
  externalName: {{ .externalName }}
  ports:
    - protocol: TCP
      port: {{ .internalPort }}
      targetPort: {{ .externalPort }}
{{- else if .externalIp }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $root.Values.namespace }}
spec:
  type: {{ .type }}
  ports:
    - protocol: TCP
      port: {{ .internalPort }}
      targetPort: {{ .externalPort }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: {{ .name }}
  namespace: {{ $root.Values.namespace }}
subsets:
  - addresses:
      - ip: {{ .externalIp }}
    ports:
      - port: {{ .externalPort }}
{{ end }}
---
{{ end }}
