{{ if .Values.secret.enable }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Values.namespace }}
stringData:
  application-secret.yaml: |
{{ .Values.secret.secretData | b64enc | nindent 4 }}
{{ end }}