{{ if .Values.secret.enable }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Values.name }}-secret
  namespace: {{ .Values.namespace }}
stringData:
  application-secret.yaml: |
{{ .Values.secret.secretData | nindent 4 }}
---
{{- range .Values.subsets }}
{{ if and .secret .secret.secretData }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ $.Values.name }}-secret-{{ .name }}
  namespace: {{ $.Values.namespace }}
stringData:
  application-secret.yaml: |
{{ .secret.secretData | nindent 4 }}
{{ end }}
{{ end }}
{{ end }}