{{ if .Values.monitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.name }}-service-monitor
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    release: prometheus
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  endpoints:
  - port: http
    path: /actuator/prometheus
    interval: {{ .Values.monitor.service.interval }}
{{ end }}