name: spring
namespace: default
replicas: 1
springContainer:
  image: ghcr.io/jaewonleekor/spring-ping
  version: 0.0.2
  imagePullPolicy: IfNotPresent
  profile: dev
  aws:
    bedrock_access_key_id: ""
    bearer_token_bedrock: ""
    region: ""
config:
  enable: false
  configData: |
    server:
      port: 8080
secret:
  enable: false
  secretData: |
    secret: this-is-secret
service:
  type: NodePort
  port: 8080
externalService: []
#  - name: nosql-external-service
#    internalPort: 6379
#    externalIp: localhost
#    externalPort: 6379
#    type: ClusterIP # CNAME으로 연결할 경우 ExternalName
