name: Spring Helm package CI

on:
  push:
    branches:
      - 'main'
    paths:
      - 'spring-chart/**'

jobs:
  packaging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.0

      - name: Package Helm Chart
        run: |
          mkdir tmp
          helm package spring-chart -d tmp

      - name: Clone package repo
        env:
          PACKAGE_REPO: https://github.com/LGCNS-FINAL-LGCMS/infra-helm-packages.git
        run: |
          git clone $PACKAGE_REPO

      - name: Copy tgz to package repo
        run: |
          cp tmp/*.tgz infra-helm-packages/

      - name: Commit and Push to package repo
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: github-actions@github.com
          USER_NAME: jaewonLeeKOR
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        run: |
          cd infra-helm-packages
          helm repo index .
          git config user.name "$GIT_AUTHOR_NAME"
          git config user.email "$GIT_AUTHOR_EMAIL"
          git add .
          git commit -m "Add new helm package $(date +"%Y-%m-%d %H:%M:%S")"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/LGCNS-FINAL-LGCMS/infra-helm-packages.git
