apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: nginx-server
          {{ with .Values.nginxContainer }}
          image: {{ .image }}:{{ .version }}
          imagePullPolicy: {{ .imagePullPolicy }}
          ports:
            - containerPort: 80
            - containerPort: 443
          {{ end }}
