apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      targetPort: 80
      protocol: TCP
      name: http
    - port: {{ .Values.service.https.port }}
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    app: {{ .Values.name }}
